# Generated by Django 3.2.4 on 2021-06-08 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0010_auto_20210607_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='static/theblog/images/defaultpic.jpg', null=True, upload_to='images/profile/'),
        ),
    ]
