# Generated by Django 3.2.4 on 2021-06-10 08:25

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0012_auto_20210608_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='coba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testmce', tinymce.models.HTMLField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click Link To Read Blog Post...', max_length=255),
        ),
    ]
